name: Deploy to Databricks

on:
  workflow_dispatch:  # Trigger manually from GitHub UI
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    name: Deploy bundle to development
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  

      - name: Install dependencies from requirements.txt
        run: |
          cd dab_retail
          pip install -r requirements.txt  # Install dependencies from dab_retail/requirements.txt

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@v0.2029.0  # Specify Databricks CLI version to ensure compatibility

      - name: Authenticate with Databricks (via PAT)
        run: |
          databricks configure --host ${{ secrets.DATABRICKS_HOST }} --token ${{ secrets.DATABRICKS_TOKEN }}

      - name: Deploy the Databricks Asset Bundle
        run: |
          cd dab_retail
          databricks bundle validate  # Validate the bundle before deployment
          databricks bundle deploy --target development  # Deploy the bundle to the development target
