name: Deploy to Databricks

on:
  workflow_dispatch:  # Trigger manually from GitHub UI
  push:
    branches:
      - main  # Trigger on push to the main branch

WORKSPACE_ENV: dev

jobs:
  deploy:
    name: Deploy bundle to development
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13' 

      - name: Install dependencies from requirements.txt
        run: |
          cd dab_trips
          pip install -r requirements-dev.txt  # Install dependencies from dab_retail/requirements.txt

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main # Specify Databricks CLI version to ensure compatibility

      - name: Deploy the Databricks Asset Bundle
        run: |
          cd dab_trips
          databricks bundle validate  # Validate the bundle before deployment
          databricks bundle deploy --target $WORKSPACE_ENV  # Deploy the bundle to the development target
          databricks sync . $WORKSPACE_PROJECT_PATH --full
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
