name: Deploy to Databricks

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Deployment environment (dev, staging, prod)'
        required: true
        default: 'dev'
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Databricks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          cd dab_trips
          pip install -r requirements-dev.txt

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy the Databricks Asset Bundle
        run: |
          cd dab_trips
          ENV="${{ github.event.inputs.env || 'dev' }}"
          echo "Environment: $ENV"
          echo "Project path: $PROJECT_PATH"
          databricks bundle validate
          databricks bundle deploy --target "$ENV"
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
